quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521/ORCL
quarkus.datasource.username=RM561226
quarkus.datasource.password=110505

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

quarkus.http.port=${PORT:8080}

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,https://gs-final.vercel.app
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.exposed-headers=Location
quarkus.http.cors.access-control-allow-credentials=true
