quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,https://lashdesigner-api-1.onrender.com
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true
